### ISSUE TITLE
Loop after install

### ISSUE THREAD

**Issue by dralldev** [xevidos/codiad#2]
https://github.com/Codiad/Codiad/issues/1108#issuecomment-480599214

**Comment by xevidos** [comment]
@Niemand112233,
Did you pull from the main branch to install, the development branch to install, or did you use the update script? Also what do you mean an update loop? As in there is always an update to install or your page is not loading properly after an update?

**Comment by xevidos** [comment]
It has been more than 20 days without any activity.  I am going to close this issue until more information can be gathered.
